### ISSUE TITLE
Example vcl

### ISSUE THREAD

**Issue by yunchih** [dasebe/AdaptSize#2]
Hi, AdaptSize developers:

Thanks for this awesome framework!  I'm not sure how to write an appropriate Varnish `vcl` file to make AdaptSize work.  Would you mind giving an example?

Thanks

**Comment by dasebe** [comment]
Hi @yunchih :
You're making a good point, we were missing an example VCL. We've added this to the instructions as a [new section](https://github.com/dasebe/AdaptSize/blob/master/README.md#step-5-run-and-experiment).

This should be all you need:

      vcl 4.0;
      
      import autoparam;
      
      backend default {
             ...
      }
      
      sub vcl_backend_response {
        if (!autoparam.explru(beresp.http.Content-Length)) {
           set beresp.uncacheable = true;
           set beresp.ttl = 0s;
           return (deliver);
        }
      }

Does this help with setting things up?

**Comment by yunchih** [comment]
Thank you @dasebe !  It helps!
