### ISSUE TITLE
AdaptSize Object Hit Ratio

### ISSUE THREAD

**Issue by andxeg** [dasebe/AdaptSize#3]
Hi, AdaptSize developers.

Your results are really outstanding. 

I have read dozens of articles about caching algorithms in 
Content Delivery Network (CDN) and none of the considering algorithm 
when caching was not taken into account the size of the content
and in general all the algorithms have always added a new content ("newcomer") 
and have only relied on the policy of eviction from the cache.

I am interested in caching algorithms, read a lot of articles but
couldn't understand why researchers don't condider the size of the content,
after all the size of the content is very influence on the cache system performance.

When I has read Your article 
"AdaptSize: Orchestrating the Hot Object Memory Cache in a Content Delivery Network",
I was very pleased that our thoughts coincided.

Your article is unique in all senses: there is a good mathematical model, there is a very detailed 
study of the algorithm performance compared to existing algorithms, and besides all this there is
also the implementation (in our time reference for the implementation of the algorithms from the 
articles are often absent). But in order to develop science, it is very important to be able to 
repeat the experiments described in scientific papers, and this can only be done having a detailed 
description of the experiment (describe the requirements to the computing system, description of 
dataset) or implementation. Your article has it all.

When I read article I wanted to repeat the results from the article.

I downloaded AdaptSize, webtracereplay, webcachesim repositories.
Then I launched all algorithms in webcacesim and also AdaptSize (with webtracereplay) 
on my own datasets. And it turned out that the results AdaptSize lower than 
all the rest algorithms (LRU, LRU-K, S4LRU, LFU-DA and etc).

There is a pure implementation (not as a part of varnish) of the AdaptSize 
algorithm like implementations for webcachesim?

Or I can take from some place test data to repeat the experiment?

I've been looking for so long an article that takes into account the size of the content.
I really want to repeat the results that You presented in your article.

**Comment by dasebe** [comment]
We discussed this via email, haven't we?
Were you able to resolve this issue?

**Comment by andxeg** [comment]
I think that everything works as it should. Sorry for the late reply. Thank You so much for your help.
